- name: Update and upgrade apt packages
  apt:
    upgrade: true
    update_cache: true
    autoremove: true
    cache_valid_time: 86400

- name: Install packages
  apt:
    state: present
    pkg:
      - git
      - vim
      - rsync
      - curl
      - bat
      - nfs-common

- name: Localization
  include_tasks:
    file: localization.yml

- name: Console
  include_tasks:
    file: console.yml

- name: Aliases
  lineinfile:
    dest: /etc/bash.bashrc
    regexp: "^alias cat=.+$"
    line: "alias cat=batcat"

# - name: Network
#   include_tasks:
#     file: network.yml

- name: Mount points
  include_tasks:
    file: mountpoints.yml
