- name: Check if /usr/share/keymaps exists
  stat:
    path: /usr/share/keymaps
  register: keymaps_stat

- name: Download kbd tarball if keymaps directory does not exist
  get_url:
    url: "{{ kbd_tarball_url }}"
    dest: "/tmp/kbd-{{ kbd_version }}.tar.gz"
  when: not keymaps_stat.stat.exists

- name: Extract kbd tarball
  unarchive:
    src: "/tmp/kbd-{{ kbd_version }}.tar.gz"
    dest: "/tmp/"
    remote_src: yes
  when: not keymaps_stat.stat.exists

- name: Copy keymaps from extracted directory to /usr/share/keymaps
  copy:
    src: "{{ kbd_extract_dir }}/data/keymaps/"
    dest: /usr/share/keymaps/
    owner: root
    group: root
    mode: "0755"
    remote_src: yes
    validate: "test -d {{ item }}"
  with_fileglob:
    - "{{ kbd_extract_dir }}/data/keymaps/*"
  when: not keymaps_stat.stat.exists

- name: Set keymap using localectl
  command: localectl set-keymap "{{ common_keymap }}"
  register: localectl_output
  when: keymaps_stat.stat.exists

- name: Debug localectl output
  debug:
    var: localectl_output

- name: Check if keymap was successfully set
  assert:
    that:
      - localectl_output.rc == 0 # Check if the command was successful
    fail_msg: "Keymap change failed!"
    success_msg: "Keymap change succeeded!"

- name: Ensure console-setup and keyboard-configuration packages are installed
  apt:
    name:
      - console-setup
      - keyboard-configuration
    state: present
    update_cache: yes

- name: Check if keymaps are available
  command: localectl list-keymaps
  register: keymaps
  changed_when: false
  failed_when: false

- name: Debug keymaps available
  debug:
    var: keymaps.stdout

- name: Set keymap to "{{ common_keymap }}" using localectl
  command: localectl set-keymap "{{ common_keymap }}"
  when: "'{{ common_keymap }}' in keymaps.stdout | lower"
  notify:
    - Restart keyboard configuration

- name: Assert that the keymap is set correctly using localectl status
  assert:
    that:
      - "'Keymap: {{ common_keymap }}' in localectl_status.stdout"
    fail_msg: "Keymap change failed!"
    success_msg: "Keymap set correctly"
  when: keymaps.stdout is defined and keymaps.stdout | length > 0

- name: Setting keyboard layout to "{{ common_keymap }}" in /etc/default/keyboard (fallback)
  lineinfile:
    dest: /etc/default/keyboard
    state: present
    regexp: "^XKBLAYOUT="
    line: "XKBLAYOUT='{{ common_keymap }}'"
    create: yes

- name: Verify fallback keyboard layout by checking /etc/default/keyboard
  shell: 'cat /etc/default/keyboard | grep XKBLAYOUT | cut -d''='' -f2 | sed ''s/"//g'''
  register: fallback_kbdlayout
  when: keymaps.stdout is defined and keymaps.stdout | length > 0

- name: Assert that the fallback keymap is set correctly
  assert:
    that:
      - '(fallback_kbdlayout.stdout | replace("''", "") | trim) == common_keymap'
    fail_msg: "Fallback keyboard layout setting failed!"
    success_msg: "Fallback keyboard layout set correctly!"
  when: keymaps.stdout is defined and keymaps.stdout | length > 0

- name: Force reconfigure keyboard in non-interactive mode
  command: dpkg-reconfigure keyboard-configuration -f noninteractive
  args:
    creates: /etc/default/keyboard
  when: keymaps.stdout is defined and keymaps.stdout | length > 0 and
    (lookup('file', '/etc/default/keyboard') is not search('XKBLAYOUT={{ common_keymap }}'))
