- name: Check current keyboard layout
  shell: 'cat /etc/default/keyboard | grep XKBLAYOUT | cut -d''='' -f2 | sed ''s/"//g'''
  register: kbdlayout

- name: Change keymap "{{ kbdlayout.stdout }}" to "{{ common_keymap }}"
  block:
    - name: Set keymap to "{{ common_keymap }}" using localectl
      command: localectl set-keymap "{{ common_keymap }}"
    - name: Verify keymap using localectl
      shell: localectl | grep "VC Keymap" | cut -d ' ' -f 4
      register: new_kbdlayout
    - name: Assert that the keymap is set correctly
      assert:
        that:
          - new_kbdlayout.stdout == common_keymap
        fail_msg: "Keymap change failed!"
        success_msg: "Keymap set correctly"
  rescue:
    - name: Setting keyboard layout to "{{ common_keymap }}"
      lineinfile: 
        dest: /etc/default/keyboard
        state: present
        regexp: '^XKBLAYOUT='
        line: "XKBLAYOUT='{{ common_keymap }}'"
        create: yes
    - name: Verify fallback keyboard layout
      shell: 'cat /etc/default/keyboard | grep XKBLAYOUT | cut -d''='' -f2'
      register: fallback_kbdlayout
    - name: Assert that the fallback keymap is set correctly
      assert:
        that:
          - fallback_kbdlayout.stdout == common_keymap
        fail_msg: "Fallback keyboard layout setting failed!"
        success_msg: "Fallback keyboard layout set correctly"
  when: kbdlayout.stdout != common_keymap

- name: Update keyboard configuration and trigger dpkg-reconfigure
  command: dpkg-reconfigure keyboard-configuration
  when: kbdlayout.stdout != common_keymap
  notify: dpkg-reconfigure keyboard-configuration
