- name: Check current keyboard layout
  shell: 'cat /etc/default/keyboard | grep XKBLAYOUT | cut -d''='' -f2 | sed ''s/"//g'''
  register: kbdlayout

- name: Debug current keyboard layout
  debug:
    msg: "Current keyboard layout is {{ kbdlayout.stdout }}"

- name: Set keymap to "{{ common_keymap }}" using localectl
  command: localectl set-keymap "{{ common_keymap }}"
  register: localectl_output

- name: Debug localectl output
  debug:
    msg: "localectl output: {{ localectl_output }}"

- name: Verify keymap by checking /etc/default/keyboard file
  shell: 'cat /etc/default/keyboard | grep XKBLAYOUT | cut -d''='' -f2 | sed ''s/"//g'''
  register: new_kbdlayout

- name: Debug new keymap after applying localectl
  debug:
    msg: "New keymap after applying localectl: {{ new_kbdlayout.stdout }}"

- name: Check the current system keymap using localectl status
  command: localectl status
  register: localectl_status

- name: Debug localectl status output
  debug:
    msg: "Localectl status output: {{ localectl_status.stdout }}"

- name: Assert that the keymap is set correctly using localectl status
  assert:
    that:
      - "'Keymap: {{ common_keymap }}' in localectl_status.stdout"
    fail_msg: "Keymap change failed!"
    success_msg: "Keymap set correctly"

- name: Setting keyboard layout to "{{ common_keymap }}" (fallback)
  lineinfile: 
    dest: /etc/default/keyboard
    state: present
    regexp: '^XKBLAYOUT='
    line: "XKBLAYOUT='{{ common_keymap }}'"
    create: yes

- name: Verify fallback keyboard layout by checking /etc/default/keyboard
  shell: 'cat /etc/default/keyboard | grep XKBLAYOUT | cut -d''='' -f2 | sed ''s/"//g'''
  register: fallback_kbdlayout
  
- name: Debug fallback keymap value
  debug:
    var: fallback_kbdlayout.stdout

- name: Debug fallback keymap output after trimming
  debug:
    msg: "Fallback keyboard layout output: '{{ fallback_kbdlayout.stdout }}'"    

- name: Debug fallback keymap value (as raw)
  debug:
    var: fallback_kbdlayout.stdout

- name: Assert that the fallback keymap is set correctly
  assert:
    that:
      - "fallback_kbdlayout.stdout | trim | regex_replace('^''(.*)''$', '\\1') == common_keymap"
    fail_msg: "Fallback keyboard layout setting failed!"
    success_msg: "Fallback keyboard layout set correctly!"

- name: Force reloading the keyboard configuration
  command: dpkg-reconfigure keyboard-configuration
  when: kbdlayout.stdout != common_keymap
