---
- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - install-all
    - install-common
