- name: Create the mount directory
  ansible.builtin.file:
    path: "{{ disk.mount_path }}"
    state: directory
    mode: "0755"

- name: Perform the mounting on the mount device
  ansible.builtin.mount:
    fstype: "{{ disk.type }}"
    src: "{{ disk.src }}"
    path: "{{ disk.mount_path }}"
    state: mounted
